version: '3'

volumes:
  esdata:

services:
    elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
      environment:
        - bootstrap.memory_lock=true
        - cluster.name=es-docker-cluster
        - transport.host=127.0.0.1
        - ES_JAVA_OPTS=-Xms2g -Xmx2g # reminder to make this a global var opt
        - xpack.security.enabled=false
      volumes:
        - esdata:/usr/share/elasticsearch/data
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - "9200:9200"

    kibana:
      image: docker.elastic.co/kibana/kibana:7.6.2
      environment:
        - server.name="200410-kibana"
        - server.host="127.0.0.1:5601"
        - elasticsearch.url="http://elasticsearch:9200"
      ports:
        - "5601:5601"
      depends_on:
        - "elasticsearch"

    logstash:
      image: docker.elastic.co/logstash/logstash:7.6.2
      volumes:
      #Make sure that you create the directories first and put your configs and data in the correct location.
      - ./logstash_conf/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash_conf:/config
      - /home/shanna/data:/data
      #I generally run with debug just in case there are issues
      command: logstash --debug
      ports:
        - "5959:5959"
      depends_on:
        - "elasticsearch"
